### ISSUE TITLE
How does this work exactly?

### ISSUE THREAD

**Issue by VigneshSahoo** [tbaltrushaitis/roulette-predictor#1]
How does this work exactly? Can I use an excel file for updating gameplay?

**Comment by tbaltrushaitis** [comment]
Hi!

It developed for real-time analyzis. User should input values by clicking on the board with numbers. This tool should be used as a helper to predict next values. There is no automation on prediction.
Configurable widgets and data in tables should help to make a decision on bet.

Regards!

**Comment by toymachine247** [comment]
Hi, can you explain what the configurable are on the widgets?

**Comment by tbaltrushaitis** [comment]
> Hi, can you explain what the configurable are on the widgets?

Hi!

There are two numbers - steps count on the roulette wheel from latest round value - clockwise and counterclockwise accordingly.

![roulette-widget-configuration](https://github.com/user-attachments/assets/cc85c38a-19eb-47ed-bddd-602c244d4a9c)

**Comment by toymachine247** [comment]
Hi,

Thx for response.

There are 2 widgets per last number with set steps 0/10 n 0/5 sometimes it
changes to 3/5.

How do i interpret this?

regards,

Yaseen Mansoor

**Comment by tbaltrushaitis** [comment]
> How do i interpret this?

Its up to you.

Regards
