### ISSUE TITLE
need a coder

### ISSUE THREAD

**Issue by fadijbp** [tbaltrushaitis/roulette-predictor#10]
so t

**Comment by tbaltrushaitis** [comment]
Hi, @fadijbp !

Please contact me by email with `[ROULETTE-PREDICTOR]` in the subject.

Thank you!

**Comment by fadijbp** [comment]
I can not find your contact information. my email is jimmydean6911@gmail.com i please send me an email so i can message you back I look forward to this

**Comment by tbaltrushaitis** [comment]
Message sent ✔️

**Comment by fadijbp** [comment]
did you recieve my message and attachment?

**Comment by tbaltrushaitis** [comment]
@fadijbp 

Yes, received. Will reply soon.

Thank you!
