### ISSUE TITLE
missing number buttons

### ISSUE THREAD

**Issue by only4everock** [tbaltrushaitis/roulette-predictor#14]
Hi I installed all dependencies and build without error , but when I open index .html it shows no number enter section why is that? here is a screenshot.
https://ibb.co/d4kyWz6

**Comment by edarlea1** [comment]
hi. I am using namecheap, got a few hurdles, cannot get the app to load. had several issues when running the configuration files, but finally got this output

returncode: 0
stdout:
> roulette-predictor@0.0.1 build /home/azinptgt/roulettewiz.com/roulette-predictor-master
> gulp build

[17:17:37] Using gulpfile ~/roulettewiz.com/roulette-predictor-master/gulpfile.js
[17:17:37] Starting 'bower2src'...
[2023-06-06T21:17:37.706Z][gulp-tasks/bower2src] ACTIVATED with modConfig = [{ xhr_timeout: [33m5000[39m }]
PackageCollection add                     admin-lte         /home/azinptgt/roulettewiz.com/roulette-predictor-master/bower_modules/admin-lte
PackageCollection add                     animate.css       /home/azinptgt/roulettewiz.com/roulette-predictor-master/bower_modules/animate.css
PackageCollection add                     bootstrap         /home/azinptgt/roulettewiz.com/roulette-predictor-master/bower_modules/bootstrap
PackageCollection add                     chart.js          /home/azinptgt/roulettewiz.com/roulette-predictor-master/bower_modules/chart.js
PackageCollection add                     font-awesome      /home/azinptgt/roulettewiz.com/roulette-predictor-master/bower_modules/font-awesome
PackageCollection add                     jquery            /home/azinptgt/roulettewiz.com/roulette-predictor-master/bower_modules/jquery
PackageCollection add                     jquery-knob       /home/azinptgt/roulettewiz.com/roulette-predictor-master/bower_modules/jquery-knob
PackageCollection add                     jquery-tmpl       /home/azinptgt/roulettewiz.com/roulette-predictor-master/bower_modules/jquery-tmpl
PackageCollection add                     noty              /home/azinptgt/roulettewiz.com/roulette-predictor-master/bower_modules/noty
PackageCollection add                     requirejs         /home/azinptgt/roulettewiz.com/roulette-predictor-master/bower_modules/requirejs
PackageCollection add                     underscore        /home/azinptgt/roulettewiz.com/roulette-predictor-master/bower_modules/underscore
[17:17:37] Finished 'bower2src' after 41 ms
[17:17:37] Starting 'build'...
[17:17:37] Finished 'build' after 60 μs

as per the image attached those are my settings
![image](https://github.com/tbaltrushaitis/roulette-predictor/assets/16321870/854f07fa-dc6d-4e39-bd00-0e6f7c3f1f46)

but when I go to where I set the "app" https://roulettewiz.com/ is just shows "Error 503. Service Unavailable"

any input?

**Comment by tbaltrushaitis** [comment]
Hi, @only4everock !

Looks strange.
Please ensure that element with selector `#box-roulette-board > div.box-body.collapse.in` exists in page's html code.

Thank you!
