### ISSUE TITLE
Cannot deploy/install app

### ISSUE THREAD

**Issue by edarlea1** [tbaltrushaitis/roulette-predictor#15]
hi there, the first attempt I corrected the below errors how I saw fit and it didn't work. So I am turning to you for guidance. I'm using cpanel, my site's link will be [here ](https://roulettewiz.com/rp/1/) and now it just shows the famous "it works" :) but it doesn't work

error once I run the Run JS Script

****error****
returncode: 1
stdout:
> roulette-predictor@0.0.1 build /home/azinptgt/roulettewiz.com/rp
> gulp build

[05:58:01] Using gulpfile ~/roulettewiz.com/rp/gulpfile.js
stderr:
npm WARN lifecycle The node binary used for scripts is /home/azinptgt/nodevenv/roulettewiz.com/rp/10/bin/node but npm is using /opt/alt/alt-nodejs10/root/usr/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.
WARNING: NODE_ENV value of 'production' did not match any deployment config file names.
WARNING: See https://github.com/lorenwest/node-config/wiki/Strict-Mode
[05:58:01] Task 'bower2src' is not in your gulpfile
[05:58:01] Please check the documentation for proper gulpfile formatting
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! roulette-predictor@0.0.1 build: `gulp build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the roulette-predictor@0.0.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/azinptgt/.npm/_logs/2023-06-08T09_58_01_443Z-debug.log

****end error***

thoughts please? and thank you

**Comment by tbaltrushaitis** [comment]
Hi!

You stated that `once I run the Run JS Script` but instead you should use `make` command as stated in documentation.

Regards!
