### ISSUE TITLE
It dont open any more can you maybe fix this ?! 

### ISSUE THREAD

**Issue by Hojasroulett** [tbaltrushaitis/roulette-predictor#18]
The program wont open any more can you maybe do som thing about it?

**Comment by tbaltrushaitis** [comment]
Hi, @Hojasroulett !

With this repository I do not provide any customer service and do not guarantee that any mentioned DEMOs work described moreover - that they are working 24/7/365. 
There is a war in my country for the last 2 years and I do not have a persistent job thus do not have possibility to pay for hosting in a timely manner. 
So plase take this with an understanding if something SHOULD but DON'T work on my side...

Thank you!
