### ISSUE TITLE
Documentation on how to use

### ISSUE THREAD

**Issue by miiraheart** [tbaltrushaitis/roulette-predictor#2]
Hi I would like to know how to actually read the details in the widgets tabs and on which is going to be the next correct slot. A guide or a video on how to use the tool would be helpful. The analysis is straight forward but I'm having issues reading the predictions details and on how to figure out the correct next roulette slot

**Comment by rajkiran557** [comment]
How to read the widgets?

**Comment by Figu3redo** [comment]
I'm trying to use the roulette program, but I can't, do you have a tutorial?

**Comment by tbaltrushaitis** [comment]
Hi, @Figu3redo!

Please see [this](https://github.com/tbaltrushaitis/roulette-predictor/issues/8#issuecomment-1469436924).

Regards!
