### ISSUE TITLE
custom roullete setup

### ISSUE THREAD

**Issue by synthetichug** [tbaltrushaitis/roulette-predictor#3]
How could I use this program for a roulette wheel that is in numerical order like the one attached?
![1](https://user-images.githubusercontent.com/3522061/104538729-e5abe500-55c8-11eb-90dc-d64b72687b85.png)

**Comment by tbaltrushaitis** [comment]
Hi, @synthetichug!

Yes, **you can**!

For this to work, you need to change (or recommended way - add) settings for this roulette type in `data/roulettes.json` file.
Then adjust code to use those settings.
That's all!

Regards!

**Comment by tbaltrushaitis** [comment]
@synthetichug ,

if you'll add your roulette type and will keep code style formatting - your pull request will be highly appreciated.

Thank you!

**Comment by tbaltrushaitis** [comment]
Resolved in [commit](https://bitbucket.org/tbaltrushaitis/roulette-predictor/commits/a9dd30c62bf0a0993bda02012edde2c48663a252)
