### ISSUE TITLE
Explane how to use please

### ISSUE THREAD

**Issue by vinicisolivborges** [tbaltrushaitis/roulette-predictor#6]
how to use?

**Comment by vinicisolivborges** [comment]
Wich numbers i have to put in widgets? What means each camp in widgets? How i know when and how number to bet?

**Comment by tbaltrushaitis** [comment]
> Wich numbers i have to put in widgets?

Left and right 'low' numbers (which are entered by user) in widgets are: clockwise and counter-clockwise count of steps from supposed '**next win**' accordingly.

> What means each camp in widgets? 

Left and right 'high' numbers (if highlighted) - are the most likely  '**next win**' digits predicted by the system.

> How i know when and how number to bet?

In fact - the answer is more complicated but if you see that something is highlighted - it means that probability of numbers inside to become '**next win**' is high.

**Comment by seraffeim** [comment]
i try to play i think is verry good repo.i test it and i see some good result.ty tbal....

**Comment by tbaltrushaitis** [comment]
> i try to play i think is verry good repo.i test it and i see some good result.ty tbal....

@seraffeim , I appreciate such a greate feedback :pray: and happy that it helped you.

Thank you!

p.s. Can I close this issue now?
